---
version: "3"

services:
  conarr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/sh -c "sleep infinity"
    network_mode: service:spring-boot-admin
  spring-boot-admin:
    image: michayaak/spring-boot-admin:2.3.0
  pyconarr:
    image: tsuna77/pyconarr:0.2.2a12
    volumes:
      - ../.config/pyconarr:/home/pyconarr/config/
  wiremock:
    image: wiremock/wiremock
    volumes:
      - ../wiremock:/home/wiremock
