# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: build and test
run-name: build and test
permissions:
  contents: read
  actions: read
  checks: write

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - name: "Install dependencies"
        run: task tests

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - name: "Build"
        run: task build
      - uses: actions/upload-artifact@v4
        with:
          name: conarr
          path: dist/*
          if-no-files-found: "error"
