# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: build and test
run-name: build and test
permissions:
  contents: read
  actions: read
  checks: write

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    permissions:
      pull-requests: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - name: "Install dependencies"
        run: task init:ci

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - name: "Install dependencies"
        run: task init:ci
